region              = "us-central1"
project_id          = "clouddb-migration"
vpc_name            = "mainvpc"
database_user       = "admin"
database            = "main-db"
private_subnet_cidr = "10.0.1.0/24"
public_subnet_cidr  = "10.0.2.0/24"
